# Generated by Django 4.2.11 on 2024-04-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_profiles', '0003_registeredvotersactive_registeredvotershistorical_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterhistory',
            old_name='nc_id',
            new_name='reg_voter',
        ),
    ]
