# Generated by Django 4.2.11 on 2024-04-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_profiles', '0004_rename_nc_id_voterhistory_reg_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterHistoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='VoterFile',
            new_name='RegVoterFile',
        ),
    ]
