# Generated by Django 4.2.11 on 2024-04-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter_profiles', '0006_voterhistory_voter_registration_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterhistory',
            name='county_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voter_profiles.county'),
        ),
    ]
