# Generated by Django 4.2.11 on 2024-04-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_profiles', '0007_alter_voterhistory_county_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredvotersactive',
            name='county_comm_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='fire_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='municipal_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='municipality_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='precinct_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='prosecutorial_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='rescue_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='sanitation_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='school_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='sewer_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='township_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='voter_tab_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='ward_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotersactive',
            name='water_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='county_comm_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='fire_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='municipal_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='municipality_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='precinct_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='prosecutorial_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='rescue_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='sanitation_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='school_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='sewer_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='township_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='voter_tab_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='ward_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredvotershistorical',
            name='water_dist_desc',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='county_comm_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='fire_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='municipal_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='municipality_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='precinct_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='prosecutorial_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='rescue_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='sanitation_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='school_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='sewer_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='township_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='voter_tab_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='ward_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotersactive',
            name='water_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='county_comm_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='fire_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='municipal_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='municipality_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='precinct_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='prosecutorial_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='rescue_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='sanitation_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='school_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='sewer_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='township_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='voter_tab_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='ward_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registeredvotershistorical',
            name='water_dist_abbreviation',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='CountyCommissioner',
        ),
        migrations.DeleteModel(
            name='FireDistrict',
        ),
        migrations.DeleteModel(
            name='MunicipalDistrict',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Precinct',
        ),
        migrations.DeleteModel(
            name='ProsecutorialDistrict',
        ),
        migrations.DeleteModel(
            name='RescueDistrict',
        ),
        migrations.DeleteModel(
            name='SanitationDistrict',
        ),
        migrations.DeleteModel(
            name='SchoolDistrict',
        ),
        migrations.DeleteModel(
            name='SewerDistrict',
        ),
        migrations.DeleteModel(
            name='Township',
        ),
        migrations.DeleteModel(
            name='VoterTabulationDistrict',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.DeleteModel(
            name='WaterDistrict',
        ),
    ]
